### PR TITLE
> Added VV_Montage.pdf which is an image catalogue from

### PR DESCRIPTION
**Pull request by ranjitneel**
B.A.Vorontsov-Velyaminov. Generated by Akarsh.
> Added Arp_Montage.pdf which is an image catalogue from
Arp list. Generated by Akarsh.

### CODE REVIEW

**Comment by hrj** [comment]
Wait, this has the same problem.

What I was suggesting is to edit the release, by attaching more files to it.

Are you able to see the "Attach binaries" section here:
https://github.com/bas-org/binaries/releases/edit/vBinary

**Comment by ranjitneel** [comment]
Oh yes.
So you just want me to drop the files at "Attach binaries by dropping them
here" right ?

**Comment by hrj** [comment]
Yes, exactly.

**Comment by hrj** [comment]
I see that you have updated the files in the release. You can now link to them from anywhere, like this:

https://github.com/bas-org/binaries/releases/download/vBinary/Arp_Montage.pdf

**Comment by ranjitneel** [comment]
Done.

**Pull request closed without merging**
